// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Safeish.Data;

#nullable disable

namespace Safeish.Migrations
{
    [DbContext(typeof(SafeishDbContext))]
    [Migration("20260603173815_AddRealPackages")]
    partial class AddRealPackages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Safeish.Models.InsurancePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InsuranceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceTypeId");

                    b.ToTable("InsurancePackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverageAmount = 50000m,
                            Features = "Ayakta Tedavi (Yılda 6 Kez), Yatarak Tedavi Kapsamı, Anlaşmalı Kurum Ağı",
                            InsuranceTypeId = 1,
                            Name = "Tamamlayıcı",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 2,
                            CoverageAmount = 250000m,
                            Features = "Limitsiz Ayakta Tedavi, %100 Yatarak Tedavi, Diş ve Göz Muayenesi, Geniş Anlaşmalı Kurum",
                            InsuranceTypeId = 1,
                            Name = "Kapsamlı Sağlık",
                            Price = 7500m
                        },
                        new
                        {
                            Id = 3,
                            CoverageAmount = 1000000m,
                            Features = "Limitsiz Tüm Tedaviler, Yurtdışı Teminatı, Özel Oda ve Refakatçi, VIP Check-up, Acil Hava Ambulansı",
                            InsuranceTypeId = 1,
                            Name = "VIP Hayat",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 4,
                            CoverageAmount = 120000m,
                            Features = "Zorunlu Karşı Taraf Hasarı, Üçüncü Şahıs Koruma, Hukuki Savunma",
                            InsuranceTypeId = 2,
                            Name = "Trafik",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 5,
                            CoverageAmount = 500000m,
                            Features = "Çarpışma ve Çalınma, Doğal Afet Koruma, Cam Kırılması, Yılda 2 Kez Çekici",
                            InsuranceTypeId = 2,
                            Name = "Genişletilmiş Kasko",
                            Price = 8000m
                        },
                        new
                        {
                            Id = 6,
                            CoverageAmount = 2000000m,
                            Features = "Limitsiz İhtiyari Mali Mesuliyet, Orijinal Yedek Parça, Sınırsız İkame Araç, Hatalı Akaryakıt, Tam Koruma",
                            InsuranceTypeId = 2,
                            Name = "Premium Kasko",
                            Price = 14000m
                        },
                        new
                        {
                            Id = 7,
                            CoverageAmount = 250000m,
                            Features = "Yangın Koruma, Deprem (DASK Harici), Yer Kayması",
                            InsuranceTypeId = 3,
                            Name = "Temel Güvence",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 8,
                            CoverageAmount = 750000m,
                            Features = "Tüm Temel Kapsamlar, Hırsızlık, Su Baskını, Cam Kırılması, İzolasyon Hasarları",
                            InsuranceTypeId = 3,
                            Name = "Evim Güvende",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 9,
                            CoverageAmount = 2000000m,
                            Features = "Limitsiz Eşya Güvencesi, Elektronik Cihaz Koruma, Ücretsiz Çilingir ve Tesisat, Alternatif İkametgah",
                            InsuranceTypeId = 3,
                            Name = "Premium Konak",
                            Price = 7000m
                        },
                        new
                        {
                            Id = 10,
                            CoverageAmount = 20000m,
                            Features = "Acil Durum Müdahalesi, Kaza Sonrası Tedavi, Muayene (Yılda 2)",
                            InsuranceTypeId = 4,
                            Name = "Pati Koruma",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 11,
                            CoverageAmount = 50000m,
                            Features = "Hastalık Tedavisi, Ameliyat Masrafları, Laboratuvar Tahlilleri, Mikroçip Takılması",
                            InsuranceTypeId = 4,
                            Name = "Can Dostum",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 12,
                            CoverageAmount = 150000m,
                            Features = "Sınırsız Tedavi, Check-up, Diş Temizliği, Yurtdışı Seyahat Kapsamı, Kayıp İlan Desteği",
                            InsuranceTypeId = 4,
                            Name = "Premium Pati",
                            Price = 6000m
                        },
                        new
                        {
                            Id = 13,
                            CoverageAmount = 10000m,
                            Features = "Yurtiçi Tıbbi Tedavi, Bagaj Kaybı, Seyahat İptali",
                            InsuranceTypeId = 5,
                            Name = "Yurt İçi",
                            Price = 300m
                        },
                        new
                        {
                            Id = 14,
                            CoverageAmount = 30000m,
                            Features = "Schengen Vize Şartlarına Uygun, Tıbbi Nakil, Acil İlaç Gönderimi, Pasaport Kaybı",
                            InsuranceTypeId = 5,
                            Name = "Avrupa Vize",
                            Price = 900m
                        },
                        new
                        {
                            Id = 15,
                            CoverageAmount = 100000m,
                            Features = "Tüm Dünya Geçerli, Covid-19 Kapsamı, Hukuki Yardım, Acil Geri Dönüş, Kayak/Spor Yaralanmaları",
                            InsuranceTypeId = 5,
                            Name = "Global Gezgin",
                            Price = 1800m
                        });
                });

            modelBuilder.Entity("Safeish.Models.InsuranceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InsuranceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kapsamlı sağlık güvencesi",
                            IconUrl = "bi-heart-pulse",
                            Name = "Sağlık Sigortası"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Aracınız için tam koruma",
                            IconUrl = "bi-car-front",
                            Name = "Kasko Sigortası"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Eviniz için tam koruma",
                            IconUrl = "bi-house",
                            Name = "Konut Sigortası"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Minik dostlarınız için",
                            IconUrl = "bi-github",
                            Name = "Evcil Hayvan Sigortası"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Güvenli yolculuklar",
                            IconUrl = "bi-airplane-fill",
                            Name = "Seyahat Sigortası"
                        });
                });

            modelBuilder.Entity("Safeish.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativePhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Safeish.Models.UserPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InsurancePackageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPolicies");
                });

            modelBuilder.Entity("Safeish.Models.InsurancePackage", b =>
                {
                    b.HasOne("Safeish.Models.InsuranceType", "InsuranceType")
                        .WithMany("Packages")
                        .HasForeignKey("InsuranceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsuranceType");
                });

            modelBuilder.Entity("Safeish.Models.UserPolicy", b =>
                {
                    b.HasOne("Safeish.Models.InsurancePackage", "InsurancePackage")
                        .WithMany("Policies")
                        .HasForeignKey("InsurancePackageId");

                    b.HasOne("Safeish.Models.User", "User")
                        .WithMany("Policies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Safeish.Models.InsurancePackage", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Safeish.Models.InsuranceType", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Safeish.Models.User", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
