// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Safeish.Data;

#nullable disable

namespace Safeish.Migrations
{
    [DbContext(typeof(SafeishDbContext))]
    partial class SafeishDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Safeish.Models.InsurancePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsuranceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceTypeId");

                    b.ToTable("InsurancePackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverageAmount = 50000m,
                            Features = "Yatarak Tedavi Kapsamı, Yoğun Bakım Teminatı, Acil Durum Ambulans Hizmeti, Suni Uzuv Teminatı",
                            InsuranceTypeId = 1,
                            Name = "Temel Sağlık",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 2,
                            CoverageAmount = 150000m,
                            Features = "Temel Kapsamlar, Yılda 10 Kez Ayakta Tedavi, Ücretsiz Check-up, %80 İlaç Katılım Payı",
                            InsuranceTypeId = 1,
                            Name = "Standart Sağlık",
                            Price = 6000m
                        },
                        new
                        {
                            Id = 3,
                            CoverageAmount = 500000m,
                            Features = "Sınırsız Ayakta ve Yatarak Tedavi, Diş ve Göz Muayenesi, Yurtdışı Teminatı, Özel Oda Giderleri",
                            InsuranceTypeId = 1,
                            Name = "Premium Sağlık",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 4,
                            CoverageAmount = 250000m,
                            Features = "Çarpışma ve Çalınma, Araç Yanması, Yılda 1 Kez Çekici Hizmeti, Anahtar Kaybı (Limitli)",
                            InsuranceTypeId = 2,
                            Name = "Temel Kasko",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 5,
                            CoverageAmount = 500000m,
                            Features = "Temel Kapsamlar, Cam Kırılması, Mini Onarım, 7 Gün İkame Araç, Doğal Afetler",
                            InsuranceTypeId = 2,
                            Name = "Standart Kasko",
                            Price = 7500m
                        },
                        new
                        {
                            Id = 6,
                            CoverageAmount = 1000000m,
                            Features = "Tüm Kapsamlar, Sınırsız İkame Araç, Hatalı Akaryakıt Dolumu, Orjinal Yedek Parça",
                            InsuranceTypeId = 2,
                            Name = "Premium Kasko",
                            Price = 11000m
                        });
                });

            modelBuilder.Entity("Safeish.Models.InsuranceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InsuranceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kapsamlı sağlık güvencesi",
                            IconUrl = "bi-heart-pulse",
                            Name = "Sağlık Sigortası"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Aracınız için tam koruma",
                            IconUrl = "bi-car-front",
                            Name = "Kasko Sigortası"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Zorunlu deprem sigortası",
                            IconUrl = "bi-house",
                            Name = "DASK"
                        });
                });

            modelBuilder.Entity("Safeish.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Safeish.Models.UserPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsurancePackageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPolicies");
                });

            modelBuilder.Entity("Safeish.Models.InsurancePackage", b =>
                {
                    b.HasOne("Safeish.Models.InsuranceType", "InsuranceType")
                        .WithMany("Packages")
                        .HasForeignKey("InsuranceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsuranceType");
                });

            modelBuilder.Entity("Safeish.Models.UserPolicy", b =>
                {
                    b.HasOne("Safeish.Models.InsurancePackage", "InsurancePackage")
                        .WithMany("Policies")
                        .HasForeignKey("InsurancePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Safeish.Models.User", "User")
                        .WithMany("Policies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Safeish.Models.InsurancePackage", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Safeish.Models.InsuranceType", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Safeish.Models.User", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
